@startuml
!theme aws-orange

actor Morador
actor "Cooperativa/Catador" as Cooperativa

Morador --> (Registrar material reciclável)
Morador --> (Agendar coleta)
Morador --> (Visualizar ranking e pontuação)
Morador --> (Receber benefícios)

Cooperativa --> (Coletar material)
Cooperativa --> (Visualizar ranking dos moradores)

@enduml

